Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/ClassLength:
  Max: 130

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context', 'shared_examples']
